# One Hot Encoding
encodes categorical features or  variable as a one-hot numeric array 


the features  are  encoded using 

1. a onenote that is one of k  or
2. dummy encoding scheme

this creates a  binary column for each category

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
dataset_url = "https://raw.githubusercontent.com/shadhini/ML/main/feature_engineering/feature_encoding/res/train.csv"
df = pd.read_csv(dataset_url)

In [3]:
df.head() #top 5 rows

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.tail() # bottom 5 rows

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [5]:
df.dtypes # datatypes of each and every variable

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
## Fill missing values with NaN
df = df.fillna(np.nan)

In [7]:
## Check for Null values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
## Missing Values Imputation
# Emabarked variable
df["Embarked"].fillna("S", inplace = True)

we are going to apply the one hot  encoder  on some ***object*** variables, that are `Embarked` ad `Sex`

In [9]:
# find unique values present in our variable 'Embarked'
df["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [10]:
# find unique values present in our variable 'Sex'
df["Sex"].unique()

array(['male', 'female'], dtype=object)

when we apply the one hot encoder on  this  variable `Embarked` we will get 3 new columns  S, C, and Q  
And when we apply the one hot encoder on variable `Sex` we will get 2 new columns  male and female 

In [11]:
ohe = OneHotEncoder()
print (ohe)

OneHotEncoder()


In [12]:
feature_array = (ohe.fit_transform(df[["Embarked", "Sex"]])).toarray()
print (feature_array)

[[0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 ...
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]]


In [13]:
feature_labels = ohe.categories_
print(feature_labels)

[array(['C', 'Q', 'S'], dtype=object), array(['female', 'male'], dtype=object)]


Now, we have 2 arrays 

the first array contains categories of `Embarked`: C, Q and S  and 

the second array contains categories of `Sex`: female and male 

In [14]:
# convert categories stored in 2 different arrays in to one array
feature_labels = np.hstack(np.array(feature_labels))
print (feature_labels)

['C' 'Q' 'S' 'female' 'male']


<ipython-input-14-ae488199fabf>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  feature_labels = np.hstack(np.array(feature_labels))


In [15]:
# create dataframe of feature array
features = pd.DataFrame(feature_array, columns = feature_labels)
print(features)

       C    Q    S  female  male
0    0.0  0.0  1.0     0.0   1.0
1    1.0  0.0  0.0     1.0   0.0
2    0.0  0.0  1.0     1.0   0.0
3    0.0  0.0  1.0     1.0   0.0
4    0.0  0.0  1.0     0.0   1.0
..   ...  ...  ...     ...   ...
886  0.0  0.0  1.0     0.0   1.0
887  0.0  0.0  1.0     1.0   0.0
888  0.0  0.0  1.0     1.0   0.0
889  1.0  0.0  0.0     0.0   1.0
890  0.0  1.0  0.0     0.0   1.0

[891 rows x 5 columns]


In [16]:
# merge one hot encoded features with the original dataframe on columns (thus axis =1)
df_new = pd.concat([df, features], axis=1)
df_new.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked    C    Q    S  female  \
0      0         A/5 21171   7.2500   NaN        S  0.0  0.0  1.0     0.0   
1      0          PC 17599  71.2833   C85        C  1.0  0.0  0.0     1.0   
2      0  STON/O2. 3101282   7.9250   NaN        S  0.0  0.0  1.0     1.0   
3      0            113803  53.1000  C123        S  0.0  0.0  1.0     1.0   
4      0            373450   8.0500   NaN        S  0.0  0.0  1.0     0.0   

   male  
0   1.0  
1   0.0  
2   0.0  
3   0.0  
4   1.0